### ISSUE TITLE
Weights initialization could be suboptimal

### ISSUE THREAD

**Issue by lukovkin** [nmayorov/ufcnn#2]
In general it's advised to scale down the initial weights of neurons by the sqrt(k \* n), where n is the number of inputs and k could could be 1 or 2 depending on exact approach, see http://cs231n.github.io/neural-networks-2/ and https://github.com/fchollet/keras/blob/master/keras/initializations.py.

**Comment by nmayorov** [comment]
I'll look into that, but I think it should also depend on scales of features (i.e. take into account data preprocessing, which I believe you don't perform currently?)

**Comment by lukovkin** [comment]
No, why? We conduct features standardization prior to the training, etc.

**Comment by lukovkin** [comment]
There is an issue with weights init using inputs - we have to obtain input Tensor shape during runtime. We can pass a fixed length from the client code, but it's not very elegant.

May be weights init is not a root cause, but now we stuck ;(

**Comment by nmayorov** [comment]
OK, then, I will implement the recommended approach for initialization.

**Comment by nmayorov** [comment]
Ok, I tried to implement it as I understood it https://github.com/nmayorov/ufcnn/blob/master/ufcnn/ufcnn.py#L5

The idea is that there are `height * width * in_channels` parameters in a convolution layer, that's why I compute `n` that way.

Does it look correct?

**Comment by lukovkin** [comment]
I'm not quite sure that it's correct in terms of number if inputs. Can you refer to the Keras implementation? I'm away from computer right now.

-----Original Message-----

**Comment by nmayorov** [comment]
Yes, my version corresponds to `he_normal`.

**Comment by lukovkin** [comment]
Yeah, you're probably right. 
I took a quick look.

-----Original Message-----
