### ISSUE TITLE
Gradients are Zero on Ubuntu and Python 2.7

### ISSUE THREAD

**Issue by Mazecreator** [nmayorov/ufcnn#3]
I found an issue on my implementation of your UFCNN that caused the gradients to be 0 for all but the output layer.  I think this is related to Python handling the stddev as an integer math and rounding it to 0 most of the time:

> def init_conv_weights(shape, seed):
>     n = np.prod(shape[:-1])
>     initial = tf.random_normal(shape, stddev=(2 / n)**0.5, seed=seed)
>     return tf.Variable(initial)

Changing the initial line from 2 to 2.0 as in this:

> def init_conv_weights(shape, seed):
>     n = np.prod(shape[:-1])
>     initial = tf.random_normal(shape, stddev=(**2.0** / n)**0.5, seed=seed)
>     return tf.Variable(initial)

There are probably a few ways to force the 2/n to be treated as floats, but this worked for me.  The network now converged.

Thanks for the great work putting this together.

**Comment by nmayorov** [comment]
Thanks for the report. 

I usually keep only Python 3 in mind, but here I only need to add `from __future__ import division` which I did now.
