### ISSUE TITLE
some concern

### ISSUE THREAD

**Issue by hackerwei** [nmayorov/ufcnn#4]
In ufcnn.py +line271
C_biases = init_conv_weights([n_outputs], random_seed)
Is this right ? Seems to be:
C_biases = init_conv_bias([n_outputs], random_seed)
don't whether will cause errors.

**Comment by zekun-shi** [comment]
No, the code is correct. Biases should be initialized to 0.
See this paper for more detail https://arxiv.org/pdf/1502.01852.pdf

**Comment by nmayorov** [comment]
I think I fixed it at some point, the original concern of @hackerwei was valid.

Closing this.
